[2020-05-04 23:51:51,600] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: batch_processing.merge_files 2020-05-04T21:42:01.993735+00:00 [queued]>
[2020-05-04 23:51:51,607] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: batch_processing.merge_files 2020-05-04T21:42:01.993735+00:00 [queued]>
[2020-05-04 23:51:51,607] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-05-04 23:51:51,607] {taskinstance.py:880} INFO - Starting attempt 7 of 8
[2020-05-04 23:51:51,607] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-05-04 23:51:51,612] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): merge_files> on 2020-05-04T21:42:01.993735+00:00
[2020-05-04 23:51:51,615] {standard_task_runner.py:53} INFO - Started process 23465 to run task
[2020-05-04 23:51:51,648] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: batch_processing.merge_files 2020-05-04T21:42:01.993735+00:00 [running]> eyrunt-mbp
[2020-05-04 23:51:51,657] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-05-04 23:51:51,660] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=batch_processing, task_id=merge_files, execution_date=20200504T214201, start_date=20200504T215151, end_date=20200504T215151
[2020-05-04 23:52:01,594] {logging_mixin.py:112} INFO - [2020-05-04 23:52:01,593] {local_task_job.py:103} INFO - Task exited with return code 0
