[2020-05-04 21:04:34,420] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: batch_processing.merge_files 2020-05-02T00:00:00+00:00 [queued]>
[2020-05-04 21:04:34,428] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: batch_processing.merge_files 2020-05-02T00:00:00+00:00 [queued]>
[2020-05-04 21:04:34,428] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-05-04 21:04:34,428] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-05-04 21:04:34,428] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-05-04 21:04:34,433] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): merge_files> on 2020-05-02T00:00:00+00:00
[2020-05-04 21:04:34,435] {standard_task_runner.py:53} INFO - Started process 11601 to run task
[2020-05-04 21:04:34,475] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: batch_processing.merge_files 2020-05-02T00:00:00+00:00 [running]> eyrunt-mbp
[2020-05-04 21:04:34,485] {logging_mixin.py:112} INFO - HELLO
[2020-05-04 21:04:34,486] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-05-04 21:04:34,489] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=batch_processing, task_id=merge_files, execution_date=20200502T000000, start_date=20200504T190434, end_date=20200504T190434
[2020-05-04 21:04:44,412] {logging_mixin.py:112} INFO - [2020-05-04 21:04:44,410] {local_task_job.py:103} INFO - Task exited with return code 0
